name: "🖼️ Upload Screenshots"
description: "Uploads Screenshots taken by the Test-Script"

runs:
  using: "composite"
  steps:
    - name: ⬆️ Upload
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: /tmp/screenshot*
