on:
  push:
  pull_request:

name: 🏗️ Windows Pre-Built

jobs:
  windows-prebuilt:
    strategy:
      fail-fast: false

      matrix:
        config:
          - RelWithDebInfo
          - Release
          - Debug

    runs-on: windows-latest
    name: prebuilt-${{ matrix.config }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔨 Build
        run: |
          cmake -B build -Dsaucer_backend=WebView2 -Dsaucer_package_all=ON

          cmake --build build --config ${{ matrix.config }}
          cmake --install build --prefix 'saucer-artifact' --config ${{ matrix.config }}

      - name: 📦 Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pre-Built (${{ matrix.config }})
          path: saucer-artifact
