on:
  workflow_dispatch:
    inputs:
      debug:
        description: "Debug"
        required: false
        default: "false"
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: ["**"]

name: Test Qt5
jobs:
  test-qt5:
    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "pacman --noconfirm -Syu base-devel cmake gcc git make qt5-base qt5-webchannel qt5-webengine xorg-server-xvfb"

      - name: Debug
        uses: lhotari/action-upterm@v1
        if: ${{ github.event.inputs.debug }} == "true"
        with:
          limit-access-to-actor: true

      - name: Compile (Debug)
        run: "mkdir build && cd build && cmake .. -Dsaucer_tests=ON -Dsaucer_backend=Qt5 && cmake --build . --config Debug"

      - name: Compile (Release)
        run: "mkdir build-rel && cd build-rel && cmake .. -Dsaucer_tests=ON -Dsaucer_backend=Qt5 && cmake --build . --config Release"

      - name: Run Tests (Debug)
        run: 'QTWEBENGINE_DISABLE_SANDBOX=1 xvfb-run "./build/saucer_tests"'

      - name: Run Tests (Release)
        run: 'QTWEBENGINE_DISABLE_SANDBOX=1 xvfb-run "./build-rel/saucer_tests"'

      - name: Compile Shared (Debug)
        run: "rm -rf build && mkdir build && cd build && cmake .. -Dsaucer_wrapper=ON -Dsaucer_backend=Qt5 && cmake --build . --config Debug"

      - name: Compile Shared (Release)
        run: "rm -rf build-rel && mkdir build-rel && cd build-rel && cmake .. -Dsaucer_wrapper=ON -Dsaucer_backend=Qt5 && cmake --build . --config Release"
