on:
  workflow_dispatch:
    inputs:
      debug:
        description: "Debug"
        required: false
        default: "false"
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: ["**"]

name: Test Qt5 [Release & Debug]
jobs:
  test-qt5:
    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: "pacman --noconfirm -Syu base-devel cmake gcc git make qt5-base qt5-webchannel qt5-webengine xorg-server-xvfb"

      - if: github.event.inputs.debug == 'true'
        name: Debug
        uses: mxschmitt/action-tmate@v3
        with:
          sudo: false
          limit-access-to-actor: true

      - name: Compile [Debug Mode]
        run: "mkdir build && cd build && cmake .. -Dsaucer_tests=ON -Dsaucer_backend=Qt5 && cmake --build . --config Debug"

      - name: Run Tests [Debug Mode]
        run: 'QTWEBENGINE_DISABLE_SANDBOX=1 xvfb-run "./build/tests/saucer-tests"'

      - name: Compile [Release Mode]
        run: "mkdir build-rel && cd build-rel && cmake .. -Dsaucer_tests=ON -Dsaucer_backend=Qt5 && cmake --build . --config Release"

      - name: Run Tests [Release Mode]
        run: 'QTWEBENGINE_DISABLE_SANDBOX=1 xvfb-run "./build-rel/tests/saucer-tests"'

      - name: Compile Shared [Debug Mode]
        run: "rm -rf build && mkdir build && cd build && cmake .. -Dsaucer_wrapper=ON -Dsaucer_backend=Qt5 && cmake --build . --config Debug"

      - name: Compile Shared [Release Mode]
        run: "rm -rf build-rel && mkdir build-rel && cd build-rel && cmake .. -Dsaucer_wrapper=ON -Dsaucer_backend=Qt5 && cmake --build . --config Release"
