on:
  push:
  pull_request:

name: 🧪 Tests

jobs:
  run-tests:
    strategy:
      fail-fast: false

      matrix:
        backend:
          - Qt5
          - Qt6
        config:
          - Release
          - Debug

    name: ${{ matrix.backend }}-${{ matrix.config }}

    runs-on: ubuntu-latest
    container: archlinux:base-devel

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🛸 Setup Saucer
        uses: ./.github/actions/setup
        with:
          backend: ${{ matrix.backend }}
          platform: Linux
          build-type: ${{ matrix.config }}
          cmake-args: -Dsaucer_tests=ON -Dsaucer_ci=ON

      - name: 🧪 Test
        timeout-minutes: 10
        uses: ./.github/actions/test

      - name: 🖼️ Screenshot
        if: failure() || cancelled()
        uses: ./.github/actions/screenshot
